### ISSUE TITLE
[Question] What is the best option for intercepting Produce Request?

### ISSUE THREAD

**Issue by smoya** [grepplabs/kafka-proxy#90]
Hi,

We are building the [AsyncAPI Event-Gateway](https://github.com/asyncapi/event-gateway) (very early stage now) and we use this kafka proxy for proxying requests to remote brokers. I know this library is not 100$ built for this use case but I think It can make totally sense as most of the logic behind this package is valid for it.

Besides proxying/forwarding, we also need to intercept Produce Request messages so we can validate them (and in the future, modify them). Ideally making a chain of middlewares.
I didn't find a way to do it, so I had to temporary do some hacking in a fork so Requests have their own handlers based on the request API key. Here is the work: https://github.com/smoya/kafka-proxy/commit/a94cf71a065c1cee498c8ceb3d8153535caaf3a2 (not very nice, just a concept).

Do you believe there is a way to achieve it without modifying current code (or with minimal change?) 

Thanks!

**Comment by everesio** [comment]
Hi,
as you probably noticed only some messages are really fully decoded and interpreted by the kafka-proxy. This is done to achieve maximal performance and if it possible the messages are only streamed / passed through. Such message interception / validation is currently not possible without code changes. produce requests are the most frequent and biggest ones, so there would be a performance and memory penalty depending how the validation should be done. Additionally such implementation would add some complexity due to versioning of ProduceRequest (currently 10 versions) and different encoding of message sets / records.
